sudo: required
services:
  - docker

before_install:
  - docker build -t balenmars/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true balenmars/docker-react npm run test -- --coverage
